const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

const U = (id) => `https://images.unsplash.com/photo-${id}?w=400`;

async function main() {
  console.log('Seeding database...');

  // Categories
  const categories = await Promise.all([
    prisma.category.upsert({ where: { slug: 'makeup' }, update: {}, create: { name: 'Makeup', slug: 'makeup', description: 'Face, eye, and lip makeup', image: U('1522335789203-aabd1fc54bc9') } }),
    prisma.category.upsert({ where: { slug: 'skincare' }, update: {}, create: { name: 'Skincare', slug: 'skincare', description: 'Cleansers, moisturizers, serums', image: U('1556228578-8c89e6adf883') } }),
    prisma.category.upsert({ where: { slug: 'haircare' }, update: {}, create: { name: 'Haircare', slug: 'haircare', description: 'Shampoos, conditioners, treatments', image: U('1522337360788-8b13dee7a37e') } }),
    prisma.category.upsert({ where: { slug: 'fragrance' }, update: { image: U('1547592166-23ac45744acd') }, create: { name: 'Fragrance', slug: 'fragrance', description: 'Perfumes and body mists', image: U('1547592166-23ac45744acd') } }),
    prisma.category.upsert({ where: { slug: 'wellness' }, update: {}, create: { name: 'Wellness', slug: 'wellness', description: 'Health and wellness products', image: U('1540555700478-4be289fbecef') } }),
    prisma.category.upsert({ where: { slug: 'bath-body' }, update: { image: U('1571019613454-1cb2f99b2d8b') }, create: { name: 'Bath & Body', slug: 'bath-body', description: 'Soaps, scrubs, body lotions', image: U('1571019613454-1cb2f99b2d8b') } }),
  ]);

  // Brands
  const brands = await Promise.all([
    // existing
    prisma.brand.upsert({ where: { slug: 'lakme' }, update: {}, create: { name: 'Lakme', slug: 'lakme', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Lakme_logo.svg/200px-Lakme_logo.svg.png' } }),
    prisma.brand.upsert({ where: { slug: 'loreal' }, update: {}, create: { name: "L'Oreal", slug: 'loreal', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/L%27Or%C3%A9al_logo.svg/200px-L%27Or%C3%A9al_logo.svg.png' } }),
    prisma.brand.upsert({ where: { slug: 'maybeline' }, update: {}, create: { name: 'Maybelline', slug: 'maybeline', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Maybelline_logo.svg/200px-Maybelline_logo.svg.png' } }),
    prisma.brand.upsert({ where: { slug: 'glamcart-cosmetics' }, update: {}, create: { name: 'GlamCart Cosmetics', slug: 'glamcart-cosmetics', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'mac' }, update: {}, create: { name: 'MAC', slug: 'mac', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'forest-essentials' }, update: {}, create: { name: 'Forest Essentials', slug: 'forest-essentials', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'biotique' }, update: {}, create: { name: 'Biotique', slug: 'biotique', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'dove' }, update: {}, create: { name: 'Dove', slug: 'dove', logo: '' } }),
    // new
    prisma.brand.upsert({ where: { slug: 'neutrogena' }, update: {}, create: { name: 'Neutrogena', slug: 'neutrogena', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'mamaearth' }, update: {}, create: { name: 'Mamaearth', slug: 'mamaearth', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'wow' }, update: {}, create: { name: 'WOW Skin Science', slug: 'wow', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'fogg' }, update: {}, create: { name: 'Fogg', slug: 'fogg', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'engage' }, update: {}, create: { name: 'Engage', slug: 'engage', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'park-avenue' }, update: {}, create: { name: 'Park Avenue', slug: 'park-avenue', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'davidoff' }, update: {}, create: { name: 'Davidoff', slug: 'davidoff', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'vaseline' }, update: {}, create: { name: 'Vaseline', slug: 'vaseline', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'himalaya' }, update: {}, create: { name: 'Himalaya', slug: 'himalaya', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'mcaffeine' }, update: {}, create: { name: 'MCaffeine', slug: 'mcaffeine', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'organic-india' }, update: {}, create: { name: 'Organic India', slug: 'organic-india', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'revlon' }, update: {}, create: { name: 'Revlon', slug: 'revlon', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'minimalist' }, update: {}, create: { name: 'Minimalist', slug: 'minimalist', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'plum' }, update: {}, create: { name: 'Plum Goodness', slug: 'plum', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'tresemme' }, update: {}, create: { name: 'TRESemmé', slug: 'tresemme', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'parachute' }, update: {}, create: { name: 'Parachute', slug: 'parachute', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'nivea' }, update: {}, create: { name: 'Nivea', slug: 'nivea', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'sugar' }, update: {}, create: { name: 'SUGAR Cosmetics', slug: 'sugar', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'faces-canada' }, update: {}, create: { name: 'Faces Canada', slug: 'faces-canada', logo: '' } }),
    prisma.brand.upsert({ where: { slug: 'colorbar' }, update: {}, create: { name: 'Colorbar', slug: 'colorbar', logo: '' } }),
  ]);

  const [makeup, skincare, haircare, fragrance, wellness, bathBody] = categories;
  const [
    lakme, loreal, maybelline, glamcartCosmetics, mac, forestEssentials, biotique, dove,
    neutrogena, mamaearth, wow, fogg, engage, parkAvenue, davidoff, vaseline, himalaya,
    mcaffeine, organicIndia, revlon, minimalist, plum, tresemme, parachute, nivea, sugar, facesCanada, colorbar,
  ] = brands;

  const products = [
    // ── MAKEUP (16) ──────────────────────────────────────────────
    {
      name: 'Lakme Absolute Skin Natural Mousse Foundation',
      slug: 'lakme-absolute-skin-natural-mousse-foundation',
      description: 'Lightweight mousse foundation for a natural finish. Provides full coverage with SPF 25 protection. Available in 10 shades.',
      price: 695, mrp: 799, discount: 13,
      images: [U('1776790799226-021a8e00ce38'), U('1777390435474-9f96d60435c6')],
      stock: 150, sku: 'LAK-FND-001', rating: 4.3, reviewCount: 1247,
      categoryId: makeup.id, brandId: lakme.id,
      tags: 'foundation,mousse,coverage,spf,face', isFeatured: true, isBestSeller: true,
    },
    {
      name: 'Maybelline Fit Me Matte+Poreless Foundation',
      slug: 'maybelline-fit-me-matte-poreless-foundation',
      description: 'Naturally matte finish that minimizes pores. Controls shine for 12 hours. 40 shades for every skin tone.',
      price: 415, mrp: 525, discount: 21,
      images: [U('1776015036303-1087ac99dc4f')],
      stock: 300, sku: 'MAY-FND-001', rating: 4.2, reviewCount: 2156,
      categoryId: makeup.id, brandId: maybelline.id,
      tags: 'foundation,matte,pore minimizing,face', isBestSeller: true,
    },
    {
      name: 'GlamCart Cosmetics Wanderlust Eyeshadow Palette',
      slug: 'glamcart-wanderlust-eyeshadow-palette',
      description: '9-shade eyeshadow palette with matte, shimmer and glitter finishes. Long-lasting pigmented formula.',
      price: 649, mrp: 799, discount: 19,
      images: [U('1776015036380-4022fe844ed8')],
      stock: 120, sku: 'NYK-EYE-001', rating: 4.4, reviewCount: 567,
      categoryId: makeup.id, brandId: glamcartCosmetics.id,
      tags: 'eyeshadow,palette,shimmer,matte,eye', isFeatured: true,
    },
    {
      name: 'MAC Ruby Woo Lipstick',
      slug: 'mac-ruby-woo-lipstick',
      description: 'Iconic matte red lipstick. Retro matte formula for vivid, true-blue red color that lasts all day.',
      price: 1800, mrp: 1800, discount: 0,
      images: [U('1777499253106-81f6135ac0fb')],
      stock: 80, sku: 'MAC-LIP-001', rating: 4.8, reviewCount: 4567,
      categoryId: makeup.id, brandId: mac.id,
      tags: 'lipstick,red,matte,iconic,lips', isFeatured: true, isBestSeller: true,
    },
    {
      name: 'Lakme 9 to 5 Weightless Mousse Lip & Cheek Color',
      slug: 'lakme-9-to-5-weightless-mousse-lip-cheek',
      description: 'Ultra lightweight mousse formula for lips and cheeks. Natural look, featherlight feel. 12-hour wear.',
      price: 395, mrp: 449, discount: 12,
      images: [U('1776869749127-0ff7ecd69e66')],
      stock: 180, sku: 'LAK-LIP-001', rating: 4.1, reviewCount: 892,
      categoryId: makeup.id, brandId: lakme.id,
      tags: 'lip color,blush,mousse,natural,lips',
    },
    {
      name: 'Maybelline Colossal Kajal',
      slug: 'maybelline-colossal-kajal',
      description: 'Intense black kajal for bold, long-lasting eye looks. Waterproof formula that lasts up to 24 hours.',
      price: 149, mrp: 199, discount: 25,
      images: [U('1777028680121-ec0ebc61e642')],
      stock: 600, sku: 'MAY-EYE-001', rating: 4.6, reviewCount: 8923,
      categoryId: makeup.id, brandId: maybelline.id,
      tags: 'kajal,eye,waterproof,black,kohl', isBestSeller: true,
    },
    {
      name: "L'Oreal Paris True Match Super-Blendable Foundation",
      slug: 'loreal-true-match-foundation',
      description: 'Super-blendable foundation that matches skin tone precisely. SPF 17, dermatologist tested, available in 45 shades.',
      price: 799, mrp: 999, discount: 20,
      images: [U('1776790376585-4a12803b2b8c')],
      stock: 220, sku: 'LOR-FND-001', rating: 4.3, reviewCount: 1832,
      categoryId: makeup.id, brandId: loreal.id,
      tags: 'foundation,blendable,spf,face,coverage', isFeatured: true,
    },
    {
      name: 'Maybelline Fit Me Concealer',
      slug: 'maybelline-fit-me-concealer',
      description: 'Blends seamlessly with skin for a fresh, natural look. Covers blemishes and under-eye dark circles. 40 shades.',
      price: 299, mrp: 375, discount: 20,
      images: [U('1776273920172-5b18975dbbd3')],
      stock: 280, sku: 'MAY-CON-001', rating: 4.0, reviewCount: 1234,
      categoryId: makeup.id, brandId: maybelline.id,
      tags: 'concealer,face,blemish,dark circles,coverage',
    },
    {
      name: 'SUGAR Cosmetics Matte Attack Transferproof Lipstick',
      slug: 'sugar-cosmetics-matte-attack-lipstick',
      description: 'Highly pigmented matte lipstick that stays for 12 hours without transfer. Available in 30 bold shades.',
      price: 499, mrp: 599, discount: 17,
      images: [U('1776869749373-b0245122b15f')],
      stock: 200, sku: 'SGR-LIP-001', rating: 4.2, reviewCount: 2341,
      categoryId: makeup.id, brandId: sugar.id,
      tags: 'lipstick,matte,transfer proof,long lasting,lips', isBestSeller: true,
    },
    {
      name: 'Lakme Eyeconic Kajal',
      slug: 'lakme-eyeconic-kajal',
      description: 'Smooth, waterproof kajal for intense, smudge-free eyes. Long-wear formula that glides effortlessly.',
      price: 179, mrp: 229, discount: 22,
      images: [U('1777032524286-1ceb6b5d9975')],
      stock: 450, sku: 'LAK-KAJ-001', rating: 4.3, reviewCount: 3421,
      categoryId: makeup.id, brandId: lakme.id,
      tags: 'kajal,eye,waterproof,smudge free,kohl', isBestSeller: true,
    },
    {
      name: 'GlamCart Cosmetics Neon Lights Liquid Eyeliner',
      slug: 'glamcart-neon-liquid-eyeliner',
      description: 'Vivid neon liquid eyeliner for bold eye art. Felt-tip pen applicator for precise lines. Waterproof and long-lasting.',
      price: 349, mrp: 399, discount: 13,
      images: [U('1777028680121-ec0ebc61e642'), U('1776273920172-5b18975dbbd3')],
      stock: 160, sku: 'NYK-LIN-001', rating: 4.1, reviewCount: 445,
      categoryId: makeup.id, brandId: glamcartCosmetics.id,
      tags: 'eyeliner,liquid,neon,eye,bold',
    },
    {
      name: 'Revlon Super Lustrous Lipstick',
      slug: 'revlon-super-lustrous-lipstick',
      description: 'High-impact lipstick with moisturizing formula. Creamy and sheer finishes for all-day comfortable wear.',
      price: 699, mrp: 850, discount: 18,
      images: [U('1775642544067-c4ad1eceba5b')],
      stock: 175, sku: 'REV-LIP-001', rating: 4.2, reviewCount: 1678,
      categoryId: makeup.id, brandId: revlon.id,
      tags: 'lipstick,creamy,moisturizing,lustrous,lips',
    },
    {
      name: 'Faces Canada Ultime Pro HD Blush',
      slug: 'faces-canada-ultime-pro-hd-blush',
      description: 'High-definition blush powder for a natural flushed look. Buildable color with a silky-smooth finish.',
      price: 549, mrp: 699, discount: 21,
      images: [U('1774542248946-68aca19c901a')],
      stock: 130, sku: 'FCN-BLS-001', rating: 4.0, reviewCount: 567,
      categoryId: makeup.id, brandId: facesCanada.id,
      tags: 'blush,HD,face,powder,contour',
    },
    {
      name: 'Colorbar Matte Me Just Matte Lip Color',
      slug: 'colorbar-matte-me-lip-color',
      description: 'Lightweight, non-drying matte lip color. Intense pigmentation in one swipe. 20 stunning shades.',
      price: 425, mrp: 525, discount: 19,
      images: [U('1776869749127-0ff7ecd69e66'), U('1777499253106-81f6135ac0fb')],
      stock: 210, sku: 'CLB-LIP-001', rating: 4.1, reviewCount: 892,
      categoryId: makeup.id, brandId: colorbar.id,
      tags: 'lip color,matte,lightweight,pigmented,lips',
    },
    {
      name: "L'Oreal Paris Infallible 24H Matte Lipstick",
      slug: 'loreal-infallible-24h-matte-lipstick',
      description: '24-hour lasting matte lipstick with moisturizing comfort. High pigmentation with a velvety finish.',
      price: 649, mrp: 799, discount: 19,
      images: [U('1777032524286-1ceb6b5d9975'), U('1776790799226-021a8e00ce38')],
      stock: 190, sku: 'LOR-LIP-001', rating: 4.3, reviewCount: 1456,
      categoryId: makeup.id, brandId: loreal.id,
      tags: 'lipstick,matte,24 hour,infallible,lips', isFeatured: true,
    },
    {
      name: 'MAC Strobe Cream Illuminating Moisturizer',
      slug: 'mac-strobe-cream-illuminator',
      description: 'Iconic illuminating moisturizer that instantly creates a radiant, lit-from-within glow. Wear alone or under foundation.',
      price: 2950, mrp: 2950, discount: 0,
      images: [U('1776015036380-4022fe844ed8')],
      stock: 55, sku: 'MAC-STR-001', rating: 4.6, reviewCount: 789,
      categoryId: makeup.id, brandId: mac.id,
      tags: 'strobe cream,illuminator,glow,face,radiance', isFeatured: true,
    },

    // ── SKINCARE (10) ────────────────────────────────────────────
    {
      name: "L'Oreal Paris Revitalift Crystal Micro-Essence",
      slug: 'loreal-revitalift-crystal-micro-essence',
      description: 'Light as water micro-essence with salicylic acid to remove dead skin cells and reveal crystal clear skin.',
      price: 899, mrp: 1199, discount: 25,
      images: [U('1777396761485-85b2ac69b89a')],
      stock: 200, sku: 'LOR-SKN-001', rating: 4.5, reviewCount: 892,
      categoryId: skincare.id, brandId: loreal.id,
      tags: 'serum,essence,salicylic acid,brightening,face', isFeatured: true,
    },
    {
      name: 'Forest Essentials Soundarya Radiance Cream',
      slug: 'forest-essentials-soundarya-radiance-cream',
      description: 'Luxurious skin brightening cream with 24-karat gold and SPF 25. Ayurvedic formula for radiant skin.',
      price: 3500, mrp: 3500, discount: 0,
      images: [U('1773558057687-cf2348c40929')],
      stock: 45, sku: 'FE-SKN-001', rating: 4.7, reviewCount: 234,
      categoryId: skincare.id, brandId: forestEssentials.id,
      tags: 'luxury,ayurvedic,brightening,gold,cream', isFeatured: true,
    },
    {
      name: 'Biotique Bio Honey Gel Moisturizer',
      slug: 'biotique-bio-honey-gel-moisturizer',
      description: 'Refreshing honey gel moisturizer for oily to combination skin. Contains wild honey, dandelion and berberry extracts.',
      price: 199, mrp: 249, discount: 20,
      images: [U('1773452451137-acc5fd1c0dfd')],
      stock: 400, sku: 'BIO-SKN-001', rating: 4.1, reviewCount: 1893,
      categoryId: skincare.id, brandId: biotique.id,
      tags: 'moisturizer,gel,oily skin,honey,face', isBestSeller: true,
    },
    {
      name: 'Biotique Morning Nectar Moisturizer SPF 30',
      slug: 'biotique-morning-nectar-moisturizer-spf30',
      description: 'Daily moisturizer with SPF 30 for flawless skin. Enriched with pure honey, wheat germ and berberry extracts.',
      price: 179, mrp: 225, discount: 20,
      images: [U('1775127596257-1b913f6d32da')],
      stock: 350, sku: 'BIO-SKN-002', rating: 4.0, reviewCount: 2134,
      categoryId: skincare.id, brandId: biotique.id,
      tags: 'moisturizer,spf,daily,natural,face',
    },
    {
      name: 'Neutrogena Hydro Boost Water Gel',
      slug: 'neutrogena-hydro-boost-water-gel',
      description: 'Instantly quenches skin and keeps it looking smooth and supple. Non-comedogenic hyaluronic acid formula.',
      price: 799, mrp: 999, discount: 20,
      images: [U('1774887554034-c73a4edc3d3c')],
      stock: 220, sku: 'NEU-SKN-001', rating: 4.4, reviewCount: 1456,
      categoryId: skincare.id, brandId: neutrogena.id,
      tags: 'moisturizer,hyaluronic acid,hydrating,gel,face', isFeatured: true,
    },
    {
      name: 'Minimalist 10% Niacinamide + Zinc Serum',
      slug: 'minimalist-10-niacinamide-zinc-serum',
      description: 'High-strength niacinamide serum that reduces pores, balances sebum and fades blemishes. Dermatologically tested.',
      price: 599, mrp: 699, discount: 14,
      images: [U('1776438805326-f118ddb48b89')],
      stock: 310, sku: 'MIN-SKN-001', rating: 4.4, reviewCount: 3241,
      categoryId: skincare.id, brandId: minimalist.id,
      tags: 'serum,niacinamide,zinc,pores,blemish', isFeatured: true, isBestSeller: true,
    },
    {
      name: 'Plum Green Tea Pore Cleansing Face Wash',
      slug: 'plum-green-tea-pore-cleansing-face-wash',
      description: 'Gentle daily face wash with green tea extract that deep cleanses and minimizes pores. 100% vegan, pH-balanced.',
      price: 245, mrp: 299, discount: 18,
      images: [U('1775642542636-30a577d06996')],
      stock: 280, sku: 'PLM-SKN-001', rating: 4.2, reviewCount: 1789,
      categoryId: skincare.id, brandId: plum.id,
      tags: 'face wash,green tea,pore,cleansing,vegan',
    },
    {
      name: 'Mamaearth Ubtan Face Wash with Turmeric & Saffron',
      slug: 'mamaearth-ubtan-face-wash',
      description: 'Natural ubtan face wash with turmeric, saffron and papaya that brightens skin and removes tan.',
      price: 249, mrp: 299, discount: 17,
      images: [U('1775642548388-7dc24f226554')],
      stock: 340, sku: 'MAM-SKN-001', rating: 4.1, reviewCount: 2567,
      categoryId: skincare.id, brandId: mamaearth.id,
      tags: 'face wash,turmeric,saffron,brightening,tan removal',
    },
    {
      name: 'WOW Skin Science Retinol Serum',
      slug: 'wow-retinol-serum',
      description: 'Anti-aging retinol serum that reduces fine lines, wrinkles and uneven skin tone. Boosts collagen production.',
      price: 699, mrp: 849, discount: 18,
      images: [U('1775989982439-610be22c8c7b')],
      stock: 195, sku: 'WOW-SKN-001', rating: 4.3, reviewCount: 1124,
      categoryId: skincare.id, brandId: wow.id,
      tags: 'serum,retinol,anti aging,fine lines,collagen',
    },
    {
      name: "L'Oreal Paris Hydra Genius Daily Liquid Care",
      slug: 'loreal-hydra-genius-daily-liquid-care',
      description: 'Lightweight water-gel moisturizer with hyaluronic acid and aloe vera. Provides 72-hour hydration.',
      price: 699, mrp: 899, discount: 22,
      images: [U('1774620714979-2c258294fa48')],
      stock: 240, sku: 'LOR-SKN-002', rating: 4.2, reviewCount: 987,
      categoryId: skincare.id, brandId: loreal.id,
      tags: 'moisturizer,hyaluronic acid,aloe vera,hydration,face',
    },

    // ── HAIRCARE (7) ─────────────────────────────────────────────
    {
      name: "L'Oreal Paris Elvive Dream Lengths Shampoo",
      slug: 'loreal-elvive-dream-lengths-shampoo',
      description: 'Nourishing shampoo for long, damaged hair. With castor oil and vitamins B3 & B5 for strong, healthy growth.',
      price: 349, mrp: 399, discount: 13,
      images: [U('1776105609708-3d8908ab4dc2')],
      stock: 250, sku: 'LOR-HAIR-001', rating: 4.3, reviewCount: 678,
      categoryId: haircare.id, brandId: loreal.id,
      tags: 'shampoo,long hair,castor oil,strengthening,bottle',
    },
    {
      name: 'Mamaearth Onion Hair Oil for Hair Growth & Hair Fall Control',
      slug: 'mamaearth-onion-hair-oil',
      description: 'Reduces hair fall and promotes hair growth with the power of onion and redensyl. Mineral oil free.',
      price: 349, mrp: 399, discount: 13,
      images: [U('1773305676182-5f34519e11b6')],
      stock: 310, sku: 'MAM-HAIR-001', rating: 4.3, reviewCount: 3241,
      categoryId: haircare.id, brandId: mamaearth.id,
      tags: 'hair oil,onion,hair growth,hair fall,bottle', isBestSeller: true,
    },
    {
      name: "L'Oreal Total Repair 5 Restoring Conditioner",
      slug: 'loreal-total-repair-5-conditioner',
      description: 'Repairs 5 signs of damaged hair: breakage, roughness, dullness, dryness and split ends. With Pro-Keratin complex.',
      price: 299, mrp: 375, discount: 20,
      images: [U('1776146398875-b8c25f2efccb')],
      stock: 280, sku: 'LOR-HAIR-002', rating: 4.2, reviewCount: 934,
      categoryId: haircare.id, brandId: loreal.id,
      tags: 'conditioner,repair,damaged hair,smooth,keratin',
    },
    {
      name: 'WOW Apple Cider Vinegar Shampoo',
      slug: 'wow-apple-cider-vinegar-shampoo',
      description: 'Clarifying shampoo with apple cider vinegar that cleanses scalp build-up. Sulfate and paraben free.',
      price: 299, mrp: 349, discount: 14,
      images: [U('1775743511334-c8e7924c7676')],
      stock: 195, sku: 'WOW-HAIR-001', rating: 4.1, reviewCount: 2134,
      categoryId: haircare.id, brandId: wow.id,
      tags: 'shampoo,apple cider vinegar,clarifying,scalp,bottle', isBestSeller: true,
    },
    {
      name: 'Biotique Bio Kelp Fresh Growth Shampoo',
      slug: 'biotique-bio-kelp-shampoo',
      description: 'Protein-enriched shampoo with seaweed and mint that stimulates hair follicles for thicker, fuller growth.',
      price: 179, mrp: 220, discount: 19,
      images: [U('1775126454577-4846f3e55cc5')],
      stock: 340, sku: 'BIO-HAIR-001', rating: 3.9, reviewCount: 876,
      categoryId: haircare.id, brandId: biotique.id,
      tags: 'shampoo,hair growth,protein,kelp,bottle',
    },
    {
      name: 'TRESemmé Keratin Smooth Serum',
      slug: 'tresemme-keratin-smooth-serum',
      description: 'Keratin-infused hair serum that tames frizz and adds shine. Protects against humidity for 72 hours.',
      price: 299, mrp: 375, discount: 20,
      images: [U('1773527142309-80df44147512')],
      stock: 220, sku: 'TRS-HAIR-001', rating: 4.2, reviewCount: 1342,
      categoryId: haircare.id, brandId: tresemme.id,
      tags: 'hair serum,keratin,frizz,shine,smooth',
    },
    {
      name: 'Parachute Advansed Deep Nourish Coconut Hair Oil',
      slug: 'parachute-advansed-coconut-hair-oil',
      description: 'Enriched coconut hair oil with vitamin E for deep nourishment. Strengthens roots and adds natural shine.',
      price: 199, mrp: 249, discount: 20,
      images: [U('1772910059637-6c38cfe4226a')],
      stock: 500, sku: 'PAR-HAIR-001', rating: 4.0, reviewCount: 4521,
      categoryId: haircare.id, brandId: parachute.id,
      tags: 'hair oil,coconut,nourish,vitamin e,bottle', isBestSeller: true,
    },

    // ── FRAGRANCE (7) ────────────────────────────────────────────
    {
      name: 'Fogg Scent Woods Body Spray for Men',
      slug: 'fogg-scent-woods-body-spray',
      description: 'Long-lasting woody fragrance body spray. No gas, only perfume. 800+ sprays guaranteed.',
      price: 229, mrp: 269, discount: 15,
      images: [U('1777331736594-ee984de6c2f3')],
      stock: 500, sku: 'FOGG-FRG-001', rating: 4.2, reviewCount: 4521,
      categoryId: fragrance.id, brandId: fogg.id,
      tags: 'body spray,woody,long lasting,men,bottle', isBestSeller: true,
    },
    {
      name: 'Engage W1 Perfume Spray for Women',
      slug: 'engage-w1-perfume-spray',
      description: 'Floral and fruity perfume spray for women. Long-lasting fragrance with refreshing peach and jasmine.',
      price: 179, mrp: 199, discount: 10,
      images: [U('1777307275337-342e5ca9732a')],
      stock: 420, sku: 'ENG-FRG-001', rating: 4.0, reviewCount: 2876,
      categoryId: fragrance.id, brandId: engage.id,
      tags: 'perfume,floral,fruity,women,jasmine,bottle',
    },
    {
      name: 'Park Avenue Good Morning EDT',
      slug: 'park-avenue-good-morning-edt',
      description: 'Fresh and invigorating morning fragrance with citrus and aquatic notes. Perfect for everyday wear.',
      price: 349, mrp: 399, discount: 13,
      images: [U('1777136977184-22275ac1c31e')],
      stock: 180, sku: 'PA-FRG-001', rating: 3.8, reviewCount: 1234,
      categoryId: fragrance.id, brandId: parkAvenue.id,
      tags: 'edt,fresh,citrus,men,morning,bottle',
    },
    {
      name: 'Forest Essentials Eau de Parfum Iced Pomegranate',
      slug: 'forest-essentials-eau-de-parfum',
      description: 'Luxury Ayurvedic eau de parfum with pomegranate, rose and musk. Crafted with pure essential oils.',
      price: 3200, mrp: 3200, discount: 0,
      images: [U('1776890370639-6c4d51c63345')],
      stock: 35, sku: 'FE-FRG-001', rating: 4.6, reviewCount: 189,
      categoryId: fragrance.id, brandId: forestEssentials.id,
      tags: 'luxury,ayurvedic,parfum,rose,pomegranate,bottle', isFeatured: true,
    },
    {
      name: 'Davidoff Cool Water EDT for Men',
      slug: 'davidoff-cool-water-edt',
      description: 'Iconic aquatic fragrance with notes of spearmint, lavender and sandalwood. Fresh and long-lasting.',
      price: 2499, mrp: 3200, discount: 22,
      images: [U('1776651993626-7cc836bf03aa')],
      stock: 60, sku: 'DAV-FRG-001', rating: 4.5, reviewCount: 567,
      categoryId: fragrance.id, brandId: davidoff.id,
      tags: 'edt,aquatic,men,lavender,sandalwood,bottle', isFeatured: true,
    },
    {
      name: 'Fogg Victor Body Spray for Men',
      slug: 'fogg-victor-body-spray',
      description: 'Bold and masculine body spray with aromatic and spicy notes. 800+ sprays with no gas.',
      price: 229, mrp: 269, discount: 15,
      images: [U('1776267884755-0ec673b3d7e5')],
      stock: 480, sku: 'FOGG-FRG-002', rating: 4.1, reviewCount: 3210,
      categoryId: fragrance.id, brandId: fogg.id,
      tags: 'body spray,masculine,spicy,men,aromatic', isBestSeller: true,
    },
    {
      name: 'Engage Him Cologne Spray',
      slug: 'engage-him-cologne-spray',
      description: 'Refreshing cologne spray for men with woody and musky notes. Long-lasting fragrance for all-day confidence.',
      price: 199, mrp: 229, discount: 13,
      images: [U('1776148280128-1fb20cd4a3c9')],
      stock: 360, sku: 'ENG-FRG-002', rating: 3.9, reviewCount: 1876,
      categoryId: fragrance.id, brandId: engage.id,
      tags: 'cologne,men,woody,musky,bottle',
    },

    // ── BATH & BODY (7) ──────────────────────────────────────────
    {
      name: 'Dove Deeply Nourishing Body Wash',
      slug: 'dove-deeply-nourishing-body-wash',
      description: 'Gentle body wash with 1/4 moisturizing cream. Leaves skin feeling soft and smooth after every shower.',
      price: 185, mrp: 225, discount: 18,
      images: [U('1775642545087-315847882556')],
      stock: 500, sku: 'DOVE-BB-001', rating: 4.5, reviewCount: 3421,
      categoryId: bathBody.id, brandId: dove.id,
      tags: 'body wash,moisturizing,gentle,shower,bottle', isBestSeller: true,
    },
    {
      name: 'Vaseline Intensive Care Body Lotion',
      slug: 'vaseline-intensive-care-body-lotion',
      description: 'Fast-absorbing body lotion with micro-droplets of Vaseline jelly. Heals dry skin in just 5 days.',
      price: 225, mrp: 275, discount: 18,
      images: [U('1776241732359-e283bf413901')],
      stock: 460, sku: 'VAS-BB-001', rating: 4.4, reviewCount: 5678,
      categoryId: bathBody.id, brandId: vaseline.id,
      tags: 'body lotion,dry skin,moisturizing,healing,bottle', isBestSeller: true,
    },
    {
      name: 'Himalaya Nourishing Skin Cream',
      slug: 'himalaya-nourishing-skin-cream',
      description: 'Soft and creamy moisturizer with winter cherry and aloe vera. Keeps skin soft, smooth and hydrated.',
      price: 149, mrp: 185, discount: 19,
      images: [U('1775642548371-861fab6cea75')],
      stock: 560, sku: 'HIM-BB-001', rating: 4.0, reviewCount: 3412,
      categoryId: bathBody.id, brandId: himalaya.id,
      tags: 'skin cream,moisturizer,aloe vera,herbal,jar',
    },
    {
      name: 'Dove Shea Butter Beauty Cream Bar',
      slug: 'dove-shea-butter-beauty-cream-bar',
      description: 'Moisturizing soap bar with shea butter and warm vanilla. Leaves skin softer and smoother than regular soap.',
      price: 99, mrp: 120, discount: 18,
      images: [U('1775642548281-fcf81fd6f2a3')],
      stock: 700, sku: 'DOVE-BB-002', rating: 4.3, reviewCount: 2134,
      categoryId: bathBody.id, brandId: dove.id,
      tags: 'soap,shea butter,moisturizing,bar,bath', isBestSeller: true,
    },
    {
      name: 'Biotique Bio Walnut Bark Revitalizing Scrub',
      slug: 'biotique-bio-walnut-bark-scrub',
      description: 'Deep cleansing body scrub with walnut shell powder and almond oil. Exfoliates and refreshes dull skin.',
      price: 225, mrp: 285, discount: 21,
      images: [U('1775642545477-44baad8a5a29')],
      stock: 190, sku: 'BIO-BB-001', rating: 4.0, reviewCount: 789,
      categoryId: bathBody.id, brandId: biotique.id,
      tags: 'scrub,exfoliate,walnut,almond,body',
    },
    {
      name: 'Nivea Soft Moisturizing Cream',
      slug: 'nivea-soft-moisturizing-cream',
      description: 'Light, quick-absorbing cream with jojoba oil and vitamin E. Suitable for face, hands and body.',
      price: 175, mrp: 210, discount: 17,
      images: [U('1775642548397-c310e9a83cdf')],
      stock: 620, sku: 'NIV-BB-001', rating: 4.3, reviewCount: 6789,
      categoryId: bathBody.id, brandId: nivea.id,
      tags: 'moisturizer,cream,jojoba,vitamin e,jar', isBestSeller: true,
    },
    {
      name: 'Dove Go Fresh Cucumber & Green Tea Body Wash',
      slug: 'dove-go-fresh-cucumber-body-wash',
      description: 'Refreshing body wash with cucumber and green tea extracts. Revives and energizes skin for all-day freshness.',
      price: 210, mrp: 260, discount: 19,
      images: [U('1775642550110-158263bc1ade')],
      stock: 380, sku: 'DOVE-BB-003', rating: 4.2, reviewCount: 1876,
      categoryId: bathBody.id, brandId: dove.id,
      tags: 'body wash,cucumber,green tea,refreshing,shower',
    },

    // ── WELLNESS (6) ─────────────────────────────────────────────
    {
      name: 'MCaffeine Coffee Face Scrub',
      slug: 'mcaffeine-coffee-face-scrub',
      description: 'Exfoliating coffee face scrub that deep cleanses pores and removes tan. With walnut & hyaluronic acid.',
      price: 349, mrp: 399, discount: 13,
      images: [U('1775642543443-a10792f9dc3d')],
      stock: 270, sku: 'MCA-WEL-001', rating: 4.3, reviewCount: 2341,
      categoryId: wellness.id, brandId: mcaffeine.id,
      tags: 'face scrub,coffee,exfoliate,pore cleansing,tan removal', isFeatured: true,
    },
    {
      name: 'Mamaearth Vitamin C Face Serum',
      slug: 'mamaearth-vitamin-c-face-serum',
      description: 'Brightening face serum with 10% vitamin C and turmeric. Reduces dark spots and gives glowing skin.',
      price: 599, mrp: 699, discount: 14,
      images: [U('1775526634433-9108351b38c9')],
      stock: 230, sku: 'MAM-WEL-001', rating: 4.2, reviewCount: 1876,
      categoryId: wellness.id, brandId: mamaearth.id,
      tags: 'vitamin c,serum,brightening,dark spots,turmeric',
    },
    {
      name: 'WOW Skin Science Vitamin C Face Wash',
      slug: 'wow-vitamin-c-face-wash',
      description: 'Brightening face wash with 10% active vitamin C and niacinamide for clear, even-toned skin.',
      price: 299, mrp: 349, discount: 14,
      images: [U('1775255487971-af15499994b1')],
      stock: 310, sku: 'WOW-WEL-001', rating: 4.1, reviewCount: 1243,
      categoryId: wellness.id, brandId: wow.id,
      tags: 'face wash,vitamin c,brightening,niacinamide,cleanser', isBestSeller: true,
    },
    {
      name: 'Forest Essentials Facial Tonic Mist',
      slug: 'forest-essentials-facial-tonic-mist',
      description: 'Hydrating facial mist with pure rose water and vetiver. Sets makeup and refreshes skin throughout the day.',
      price: 1350, mrp: 1350, discount: 0,
      images: [U('1775620854129-ffebcc424f83')],
      stock: 95, sku: 'FE-WEL-001', rating: 4.5, reviewCount: 312,
      categoryId: wellness.id, brandId: forestEssentials.id,
      tags: 'facial mist,rose water,toner,hydrating,bottle', isFeatured: true,
    },
    {
      name: 'Organic India Moringa Superfood Powder',
      slug: 'organic-india-moringa-powder',
      description: 'Certified organic moringa leaf powder rich in vitamins, minerals and antioxidants. Boosts immunity and energy.',
      price: 399, mrp: 499, discount: 20,
      images: [U('1773925210700-bc2999536c1c')],
      stock: 150, sku: 'ORI-WEL-001', rating: 4.3, reviewCount: 456,
      categoryId: wellness.id, brandId: organicIndia.id,
      tags: 'moringa,superfood,organic,immunity,powder',
    },
    {
      name: 'Plum Grape Seed & Sea Buckthorn Toner',
      slug: 'plum-grape-seed-toner',
      description: 'Alcohol-free face toner with grape seed and sea buckthorn. Tightens pores and preps skin for moisturizer.',
      price: 275, mrp: 325, discount: 15,
      images: [U('1775642543751-ff2603fd7a95')],
      stock: 220, sku: 'PLM-WEL-001', rating: 4.2, reviewCount: 876,
      categoryId: wellness.id, brandId: plum.id,
      tags: 'toner,grape seed,alcohol free,pores,face',
    },
  ];

  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: { images: product.images },
      create: product,
    });
  }

  // Demo user
  const hashedPassword = await bcrypt.hash('Demo@1234', 10);
  await prisma.user.upsert({
    where: { email: 'demo@glamcart.com' },
    update: {},
    create: {
      email: 'demo@glamcart.com',
      password: hashedPassword,
      name: 'Demo User',
      phone: '9876543210',
    },
  });

  // Admin user
  const hashedAdminPassword = await bcrypt.hash('Admin@1234', 10);
  await prisma.user.upsert({
    where: { email: 'admin@glamcart.com' },
    update: { role: 'ADMIN' },
    create: {
      email: 'admin@glamcart.com',
      password: hashedAdminPassword,
      name: 'GlamCart Admin',
      phone: '9000000000',
      role: 'ADMIN',
    },
  });

  // Coupons
  const coupons = [
    { code: 'GLAMCART10', type: 'PERCENT', value: 10, minOrder: 500, maxDiscount: 200, usageLimit: 100 },
    { code: 'FIRST50',    type: 'FLAT',    value: 50, minOrder: 299, maxDiscount: 50,  usageLimit: 50  },
    { code: 'BEAUTY20',   type: 'PERCENT', value: 20, minOrder: 799, maxDiscount: 300, usageLimit: 80  },
    { code: 'SKINCARE15', type: 'PERCENT', value: 15, minOrder: 599, maxDiscount: 250, usageLimit: 80  },
    { code: 'FREESHIP',   type: 'FLAT',    value: 49, minOrder: 0,   maxDiscount: 49,  usageLimit: 200 },
    { code: 'MEGA30',     type: 'PERCENT', value: 30, minOrder: 1499,maxDiscount: 500, usageLimit: 30  },
  ];
  for (const c of coupons) {
    await prisma.coupon.upsert({
      where: { code: c.code },
      update: {},
      create: { ...c, isActive: true },
    });
  }

  console.log('Database seeded successfully!');
  console.log('Demo login:  demo@glamcart.com  / Demo@1234');
  console.log('Admin login: admin@glamcart.com / Admin@1234');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
